version: '3.8'
services:
  nodeapp:
    image: esp32-node-app
    build: .
    container_name: esp32-node-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/esp32data
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
